<form method="post">
  <ul>
    <? foreach ($fields as $field => $field_type): ?>
      <li>
        <label for="post_<?= $field ?>"><?= ucfirst($field) ?></label>
        <? if ($field_type == 'text'): ?>
          <textarea  id="post_<?= $field ?>" name="post[<?= $field ?>]"></textarea>
        <? else: ?>
           <input id="post_<?= $field ?>" name="post[<?= $field ?>]">
        <? endif; ?>
      </li>
    <? endforeach; ?>
    <li class="buttons">
      <input type="hidden" name="post[type]" value="<?= $type ?>">
      <button>Save</button>
    </li>
  </ul>
</form>