<html>
  <head>
    <title><?= $site['title'] ?></title>
    <link rel="shortcut icon" href="<?= $site['favicon'] ?>">
    <link rel="alternate" type="application/rss+xml" href="<?= $root ?>/rss">
    <link rel="stylesheet" href="<?= $root ?>/style.css">
    <? if ($site['description']): ?>
      <meta name="description" content="<?= $site['metadescription'] ?>">
    <? endif; ?>
  </head>
  <body>
    <h1><a href="<?= $root ?>"><?= $site['title'] ?></a></h1>

    <? if ($site['description']): ?>
      <p id="description"><?= $site['description'] ?></p>
    <? endif; ?>

    <?= $content_for_layout ?>
    
    <p id="footer">A Mark Zuckerberg production &bull; Powered by <a href="https://github.com/johnholdun/tumblelog">tumblelog.php</a></p>
  </body>
</html>