<html>
  <head>
    <title><?= $env['site']['title'] ?></title>
    <link rel="shortcut icon" href="<?= $env['site']['favicon'] ?>">
    <link rel="alternate" type="application/rss+xml" href="<?= $env['root'] ?>/rss">
    <link rel="stylesheet" href="<?= $env['root'] ?>/style.css">
    <? if ($env['site']['description']): ?>
      <meta name="description" content="<?= $env['site']['metadescription'] ?>">
    <? endif; ?>
  </head>
  <body>
    <h1><a href="<?= $env['root'] ?>"><?= $env['site']['title'] ?></a></h1>

    <? if ($env['site']['description']): ?>
      <p id="description"><?= $env['site']['description'] ?></p>
    <? endif; ?>

    <?= $content_for_layout ?>
    
    <p id="footer">A Mark Zuckerberg production &bull; Powered by <a href="https://github.com/johnholdun/tumblelog">tumblelog.php</a></p>
  </body>
</html>